### ISSUE TITLE
ALTER TABLE not supported

### ISSUE THREAD

**Issue by micgro42** [cosmocode/sqlite#27]
sqlite3 supports two commands with `ALTER TABLE`: `ADD COLUMN` and `RENAME TO`. Both fail with the current sqlite plugin.

Input

``` sql
ALTER TABLE ratings RENAME TO foo
```

Error Message:

```
ALTER TABLE: near "ratings": syntax error
```

Input:

``` sql
ALTER TABLE ratings ADD COLUMN foo
```

Error Message:

```
  HY000 1 near "COLUMN": syntax error:
  CREATE TEMPORARY  TABLE t1424334303 ( page, rater, lang, date, value, PRIMARY KEY(page, rater) , COLUMN foo)
```

**Comment by Klap-in** [comment]
see also 8b048386bcbdcf77fc5ef56cf46c3e28edb5af81

**Comment by splitbrain** [comment]
with #73 only native ALTER TABLE will be supported
