### ISSUE TITLE
Support not sqlite-created database files

### ISSUE THREAD

**Issue by Klap-in** [cosmocode/sqlite#29]
e.g. the Strata Plugin creates it own sqlite file. For users it could be interesting to access and query such a database via this plugin.

Currently there are two assumptions which are annoying the user:
- sqlite3 databases should have the extension `.sqlite3`
- it should have a `opts` table.

I think adding an `opts` table is only an good idea if it is really used for updating. I think it is an useful property to recognize databases created by Sqlite Plugin.
The `.sqlite3` extension is only for Sqlite Plugin to recognize the updated version database of the plugin.
So not really required for databases not created by this plugin.

See also https://github.com/bwanders/dokuwiki-strata/issues/9

Solution: 
- modify the init() function by adding an argument which allows for admin interface the use of databases without 'opts' table.
- Let admins access databases with `.sqlite` in sqlite3 which has no opts table. (assumption: all sqlite2 databases are created via Sqlite Plugin)

**Comment by splitbrain** [comment]
Hmm, the goal of this plugin is not to be a universal interface to any sqlite database, but to offer an easy way for developer to build plugins on top. I will close this as wont implement.
