### ISSUE TITLE
No strings containing question mark (?) allowed

### ISSUE THREAD

**Issue by walteruzzu** [cosmocode/sqlite#34]
adapter.php, line#169
public function prepareSql($args) {
...
$qmc = substr_count($sql, '?');
        if($argc < $qmc) {
....

The question marks should be only counted if NOT enclosed into quotes.
The way it is right now, if I try to 

INSERT INTO mytable(mycolumn) VALUES ('Hello, how are you?')

It will fail with error message
Not enough arguments passed for statement, expected 1 got 0.

**Comment by splitbrain** [comment]
You should not insert that directly. Use the following instead:

```
$sqlite->query('INSERT INTO mytable(mycolumn) VALUES (?)', array('Hello, how are you?'));
```
