### ISSUE TITLE
Complains about missing sqlite support in PHP

### ISSUE THREAD

**Issue by stbc** [cosmocode/sqlite#39]
Hi everybody,

running Debian Jessie with PHP 5.6.24 and Dokuwiki.latest. Just installed the sqlite plugin and it is complaining about missing sqlite support in php at the sqlite2 -> sqlite3 updater. See screenshot.

![screenshot-dokuwiki uni-wuppertal de 2016-07-29 10-18-26](https://cloud.githubusercontent.com/assets/2520567/17242141/d378379c-5575-11e6-9966-4f3aa267ea2a.png)

PHP has sqlite installed, as it quotes:

![screenshot-dokuwiki uni-wuppertal de 2016-07-29 10-19-48](https://cloud.githubusercontent.com/assets/2520567/17242187/11199154-5576-11e6-8897-44427e3ece70.png)
![screenshot-dokuwiki uni-wuppertal de 2016-07-29 10-20-15](https://cloud.githubusercontent.com/assets/2520567/17242188/13bdc75e-5576-11e6-9e8d-2b8b7b3889b9.png)

**Comment by splitbrain** [comment]
Yeah your PHP version does not support Sqlite2 so you need to upgrade manually.

**Comment by stbc** [comment]
Am 29.07.2016 um 10:22 schrieb Andreas Gohr:
> Yeah your PHP version does not support Sqlite2 so you need to upgrade
> manually.

Ah, thx a lot. But: where is the data directory of the plugin located?


-- 
-c

**Comment by stbc** [comment]
Ah, well, got it. data/meta. Thx
