### ISSUE TITLE
Hardcoded conf['metadir']

### ISSUE THREAD

**Issue by salsa-dev** [cosmocode/sqlite#44]
Hi, devs!

Is there are any reason the location of databases is hardcoded to `$conf['metadir']` ?

I have a need to place all the databases into `data/databases` and manage them from that directory. But also I have to edit the source code of the plugin to use the configured option like `$conf['dbdir']`.

Regards,
Serge

**Comment by splitbrain** [comment]
why? what exactly is that need?
