### ISSUE TITLE
Problem with escaping identifiers

### ISSUE THREAD

**Issue by solewniczak** [cosmocode/sqlite#47]
According to: https://sqlite.org/lang_keywords.html SQLite distinguish between two string quotations:

1. a sting literal, escaped in single quotes ''
2. an identifier, escaped in double-quotes: ""

Current implementation of \helper_plugin_sqlite::query escapes all the arguments as a string literals and it cannot be used to escape identifiers (as for example ORDER BY $something) which force programmers to concatenate the identifiers directly into SQL query string which may lead to security issue.

**Comment by annda** [comment]
@splitbrain I believe this issue is no longer relevant in the refactored version of the plugin. Can it be closed?

**Comment by splitbrain** [comment]
I guess so.
