### ISSUE TITLE
Implementation of SQLite3::createAggregate

### ISSUE THREAD

**Issue by solewniczak** [cosmocode/sqlite#48]
When we have already implemented SQLite3::createFunction \helper_plugin_sqlite_adapter_pdosqlite::create_function it will be nice to also have an SQLite3::createAggregate and SQLite3::createCollation implemented.

**Comment by splitbrain** [comment]
I haven't readded `createFunction()` in `SQLiteDB` functions can be easily added by accsing the underlying PDO object via `pdo()`.
