### ISSUE TITLE
Shouldn't pdo sqlite use the PDO prepare statement functionality?

### ISSUE THREAD

**Issue by micgro42** [cosmocode/sqlite#59]
Currently, the sqlite plugin implements its own parameter escaping and injecting in [`helper_plugin_sqlite_adapter::prepareSql`](https://github.com/cosmocode/sqlite/blob/f862eb4185adc45d49e3ebde04a50fb6e240eeaf/classes/adapter.php#L182) and this is also used in the PDO adapter.

However, PDO supports its own [`prepare`](https://www.php.net/manual/en/pdo.prepare.php), [`bindValue`](https://www.php.net/manual/en/pdostatement.bindvalue.php) and [`execute`](https://www.php.net/manual/en/pdostatement.execute.php) methods to provide that functionality. Shouldn't we use that directly, if available?

**Comment by splitbrain** [comment]
I believe this is a left over from the times of using sqlite(2). I wonder if it would be time to drop sqlite support entirely and use pdo_sqlite exclusively. However that's probably more than this issue is asking for. So if you can provide a PR for using the PDO methods, I'm happy to merge it.

**Comment by splitbrain** [comment]
will be fixed by #73
